module.exports = {
	USER_CONNECTED:"USER_CONNECTED",
	MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
	USER_DISCONNECTED:"USER_DISCONNECTED",
	TYPING:"TYPING",
	STOP_TYPING:"STOP_TYPING",
	VERIFY_USER:"VERIFY_USER",
	LOGOUT:"LOGOUT",
}
